### ISSUE TITLE
Neuer Endpunkt für gesamte Songhistorie eines anderen Nutzer

### ISSUE THREAD

**Issue by claes-work** [Music-Buddies/SGBackend#5]
Es wird ein neuer [GET] Endpunkt für das fetchen der gesamten Songhistorie eines anderen Nutzer benötigt.
In der Url übergebe ich dir die ID des Nutzers.
Das Ergebnis soll Equivalent zu folgendem Enpunkt sein:  "/user/spotify/personal-summary"

**Comment by tobi97h** [comment]
done in e77431d9158a56e9af411a4078dab2814c318c3c
