### ISSUE TITLE
Limit in GET URL

### ISSUE THREAD

**Issue by claes-work** [Music-Buddies/SGBackend#8]
Mit einem zusätzlichen Limit parameter,lösen wir unser Performance problem.
So sieht das dann in meinem GET request aus: `?limit=10`

### Wichtig

Ich bin mir nicht sicher, ob ich auch einen Wert `von - bis` in der URL übergeben kann.\
Das werden wir lanfgfristig aber brauchen.
Ziel ist, dass ich mir Beispielsweise im ProfilI die ersten 100 tracks hole und wenn ich am Ende der Seite angekommen bin die nächsten 100, als von `100 - 200` hole.

Das ist relativ wichtig, denn ich werde das jetzt erstmal auf 100 beschränken. Nur mit dem limit hätten wir momentan nicht die Möglichkeit mehr alls 100 Lieder anzuzeigen

**Comment by tobi97h** [comment]
added in 71863e50966f07345beb968c1c95847b11ab3783
