### ISSUE TITLE
Fehlende Property in Enpunkt '/together-consumed' 

### ISSUE THREAD

**Issue by claes-work** [Music-Buddies/SGBackend#9]
Beim Enpunkte `/together-consumed` bekomme ich die `listenedSeconds` zurück.\
Ich gehe davon aus, dass es sich hierbei um die Sekunden handelt, die **Ich** als Nutzer gehört habe.

Parallel dazu fehlt aber noch die Sekunden Zahl, die der **andere Nutzer** gehört hat. Die giebt es momentan noch nicht im Endpunkt.

![grafik](https://user-images.githubusercontent.com/86721650/234621141-be90ce8f-5ed7-4ccd-bfd4-3046756bde8e.png)

**Comment by tobi97h** [comment]
endpunkt gibt neues model zurück. Ein neues Feld (listenedSecondsMatch) und ein umbenanntes (listenedSeconds => listenedSecondsTogether).
